name: spent_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/img_1.png
    - lib/assets/images/img_2.png
    - lib/assets/images/img_3.png
    - lib/assets/images/img_4.png
    - lib/assets/images/img_5.jpg
    - lib/assets/images/img_6.jpg
    - lib/assets/images/img_7.jpg
    - lib/assets/images/img_8.jpg
    - lib/assets/images/img_9.jpg
    - lib/assets/images/img_10.jpg
    - lib/assets/images/img_11.jpg
    - lib/assets/images/img_12.jpg
