name: spent_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/img_1.png
    - lib/assets/images/img_2.png
    - lib/assets/images/img_3.png
    - lib/assets/images/img_4.png
    - lib/assets/images/img_5.jpg
    - lib/assets/images/img_6.jpg
    - lib/assets/images/img_7.jpg
    - lib/assets/images/img_8.jpg
    - lib/assets/images/img_9.jpg
    - lib/assets/images/img_10.jpg
    - lib/assets/images/img_11.jpg
    - lib/assets/images/img_12.jpg
    - lib/assets/images/img_13.jpg
    - lib/assets/images/img_14.jpg
    - lib/assets/images/img_15.jpg
    - lib/assets/images/img_16.jpg
    - lib/assets/images/img_17.jpg
    - lib/assets/images/img_18.jpg
    - lib/assets/images/img_19.jpg
    - lib/assets/images/img_20.jpg
    - lib/assets/images/img_21.jpg
    - lib/assets/images/img_22.jpg
    - lib/assets/images/img_23.jpg
    - lib/assets/images/img_24.jpg
    - lib/assets/images/img_25.jpg
    - lib/assets/images/img_26.jpg
    - lib/assets/images/img_r1.jpg
    - lib/assets/images/img_r2.jpg
    - lib/assets/images/img_r3.jpg
    - lib/assets/images/img_r4.jpg
    - lib/assets/images/img_r5.jpg
    - lib/assets/images/img_r6.jpg
    - lib/assets/images/img_r7.jpg
    - lib/assets/images/img_r8.jpg
    - lib/assets/images/img_r9.jpg
    - lib/assets/images/img_41.jpg
    - lib/assets/images/img_42.jpg
    - lib/assets/images/img_43.jpg
    - lib/assets/images/img_44.jpg
    - lib/assets/images/
